version: '3.5'

services:

  reverse-proxy:
    container_name: traefik
    # The official v2 Traefik docker image
    image: traefik:v2.3
    restart: always
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - ~/storage/mysql56-datadir:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    labels:
      - "traefik.tcp.routers.mysql.rule=HostSNI(`mysql.test`)"

  whoami:
    container_name: whoami
    # A container that exposes an API to show its IP address
    image: containous/whoami:v1.5.0
    restart: always
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.test`)"

  adminer:
    container_name: adminer
    image: adminer:4.7
    restart: always
    labels:
      - "traefik.http.routers.adminer.rule=Host(`adminer.test`)"

networks:
  default:
    name: local-dev
