version: '3.5'

services:

  reverse-proxy:
    container_name: traefik
    image: traefik:v2.5
    restart: always
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    logging:
      driver: none
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    labels:
      - "traefik.http.routers.mailhog.rule=Host(`mailhog.test`)"
      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - ~/storage/mysql56-datadir:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    labels:
      - "traefik.tcp.routers.mysql.rule=HostSNI(`mysql.test`)"

  whoami:
    container_name: whoami
    image: containous/whoami:v1.5.0
    restart: always
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.test`)"

  adminer:
    container_name: adminer
    image: adminer:4.8.1
    restart: always
    labels:
      - "traefik.http.routers.adminer.rule=Host(`adminer.test`)"

networks:
  default:
    name: local-dev
