version: '3.5'

services:

  app:
    image: phpearth/php:7.3-apache
    volumes:
      - ./:/var/www/localhost/htdocs
    labels:
      - "traefik.http.routers.php-73.rule=Host(`php-73.test`)"
    networks:
      - local-dev

networks:
  local-dev:
    external: true
