services:

  app:
    image: php:8.1-apache
    volumes:
      - ./:/var/www/html
    labels:
      - "traefik.http.routers.php-81.rule=Host(`php-81.test`)"
    networks:
      - local-dev

networks:
  local-dev:
    external: true
