version: '3.5'

services:

  app:
    image: php:8.3-apache
    volumes:
      - ./:/var/www/html
    labels:
      - "traefik.http.routers.php-83.rule=Host(`php-83.test`)"
    networks:
      - local-dev

networks:
  local-dev:
    external: true
