version: '3.5'

services:

  app:
    image: php:7.4-apache
    volumes:
      - ./:/var/www/html
    labels:
      - "traefik.http.routers.php-74.rule=Host(`php-74.test`)"
    networks:
      - local-dev

networks:
  local-dev:
    external: true
